# Generated by Django 3.1.4 on 2021-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_new_worker_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, null=True)),
                ('role_choices', models.CharField(choices=[('Начальник смены', 'Начальник смены'), ('Оператор', 'Оператор'), ('Водитель', 'Водитель')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
