# Generated by Django 3.1.4 on 2021-01-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_add_new_worker_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_new_worker_shift',
            options={'verbose_name': 'Добавить ФИО нач. смены, оперора, водителя', 'verbose_name_plural': 'Добавить ФИО оператором'},
        ),
    ]
