# Generated by Django 3.1.4 on 2021-02-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_customerusermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerusermodel',
            options={'ordering': ('-value2',), 'verbose_name': 'поля', 'verbose_name_plural': 'Выбор Форм для заполнения'},
        ),
        migrations.AlterField(
            model_name='customerusermodel',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AlterField(
            model_name='customerusermodel',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Видимость формы'),
        ),
    ]
