# Generated by Django 3.1.4 on 2021-03-03 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20210228_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerusermodel',
            options={'ordering': ('-value2',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиля, выбор Форм для заполнения'},
        ),
        migrations.AddField(
            model_name='customerusermodel',
            name='is_customer2',
            field=models.BooleanField(default=False, verbose_name='Видимость формы 2'),
        ),
        migrations.AlterField(
            model_name='customerusermodel',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Владелец записи, пользователь'),
        ),
        migrations.AlterField(
            model_name='customerusermodel',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Видимость формы 1'),
        ),
    ]
