# Generated by Django 3.1.4 on 2021-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210303_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerusermodel',
            old_name='author',
            new_name='user',
        ),
    ]
