# Generated by Django 3.1.4 on 2021-03-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_auto_20210303_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=False, help_text='100 characters max.', verbose_name='Видимость формы 1')),
                ('is_customer2', models.BooleanField(default=False, verbose_name='Видимость формы 2')),
                ('value1', models.CharField(max_length=100, null=True, verbose_name='ссылка')),
                ('value2', models.CharField(max_length=50, null=True, verbose_name='смена №')),
                ('value3', models.CharField(help_text='Дробилка, стружка, сушилка, клееварка, формовка, пресс, распиловка, щлифовка', max_length=50, null=True, verbose_name='Участок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи, пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиля, выбор Форм для заполнения',
                'ordering': ('-value2',),
            },
        ),
        migrations.DeleteModel(
            name='CustomerUserModel',
        ),
    ]
