# Generated by Django 3.1.4 on 2021-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210323_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileusermodel',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='is_customer2',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='value1',
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form1',
            field=models.BooleanField(default=False, help_text='Участок - Шлифовка', verbose_name='Толщина Шлифованой плиты'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form10',
            field=models.BooleanField(default=False, help_text='Участок - Пресс', verbose_name='Форма очистки лент преса'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form11',
            field=models.BooleanField(default=False, help_text='Участок - Пресс', verbose_name='Форма контроля рабочего состояния форсунок САП'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form2',
            field=models.BooleanField(default=False, help_text='Участок - Шлифовка', verbose_name='Учёт шлифовальных материалов'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form3',
            field=models.BooleanField(default=False, help_text='Участок - Шлифовка', verbose_name='Толщина пакета шлифованной плиты'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form4',
            field=models.BooleanField(default=False, help_text='Участок - Распиловка', verbose_name='Толщина пакета нешлифованой плиты'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form5',
            field=models.BooleanField(default=False, help_text='Участок - Распиловка', verbose_name='Измерение покоробленности'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form6',
            field=models.BooleanField(default=False, help_text='Участок - Распиловка', verbose_name='Учёт замены чернильной системы'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form7',
            field=models.BooleanField(default=False, help_text='Участок - Пресс', verbose_name='Производственные параметры для пресовщика'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form8',
            field=models.BooleanField(default=False, help_text='Участок - Пресс', verbose_name='Расход природного газа и древесной пыли'),
        ),
        migrations.AddField(
            model_name='profileusermodel',
            name='name_form9',
            field=models.BooleanField(default=False, help_text='Участок - Пресс', verbose_name='Толщина нешлифованой плиты'),
        ),
    ]
