# Generated by Django 3.1.4 on 2021-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210404_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='value3',
            field=models.CharField(choices=[('Шлифовка', 'Шлифовка'), ('Распиловка', 'Распиловка'), ('Пресс', 'Пресс'), ('Формовка', 'Формовка'), ('Клееварка', 'Клееварка'), ('Сушилка', 'Сушилка'), ('Стружечное', 'Стружечное'), ('Заточка', 'Заточка'), ('Дробилка', 'Дробилка')], help_text='дробилка, стружка. заточка, сушилка, клееварка, формовка, пресс, распиловка, шлифовка', max_length=50, null=True, verbose_name='Участок'),
        ),
    ]
