# Generated by Django 3.1.4 on 2021-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210404_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='value2',
            field=models.CharField(choices=[('Начальник смены 1', 'Начальник смены 1'), ('Начальник смены 2', 'Начальник смены 2'), ('Начальник смены 3', 'Начальник смены 3'), ('Начальник смены 4', 'Начальник смены 4'), ('Начальник смены 1', 'Начальник смены 1'), ('Смена 1', 'Смена 1'), ('Смена 2', 'Смена 2'), ('Смена 3', 'Смена 3'), ('Смена 4', 'Смена 4')], max_length=50, null=True, verbose_name='смена №'),
        ),
        migrations.AlterField(
            model_name='profileusermodel',
            name='value3',
            field=models.CharField(choices=[('Шлифовка', 'Шлифовка'), ('Распиловка', 'Распиловка'), ('Пресс', 'Пресс'), ('Формовка', 'Формовка'), ('Клееварка', 'Клееварка'), ('Сушилка', 'Сушилка'), ('Стружечное', 'Стружечное'), ('Заточка', 'Заточка'), ('Дробилка', 'Дробилка')], help_text='дробилка, стружка. заточка, сушилка, клееварка, формовка, пресс, распиловка, шлифовка', max_length=500, null=True, verbose_name='Участок'),
        ),
    ]
