# Generated by Django 3.1.4 on 2021-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210404_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='value2',
            field=models.CharField(choices=[('Смена 1', 'Смена 1'), ('Смена 2', 'Смена 2'), ('Смена 3', 'Смена 3'), ('Смена 4', 'Смена 4')], max_length=50, null=True, verbose_name='смена №'),
        ),
        migrations.AlterField(
            model_name='profileusermodel',
            name='value3',
            field=models.CharField(choices=[('All', 'All'), ('Шлифовка', 'Шлифовка'), ('Распиловка', 'Распиловка'), ('Пресс', 'Пресс'), ('Формовка', 'Формовка'), ('Клееварка', 'Клееварка'), ('Сушилка', 'Сушилка'), ('Стружечное', 'Стружечное'), ('Заточка', 'Заточка'), ('Дробилка', 'Дробилка')], help_text='дробилка, стружка. заточка, сушилка, клееварка, формовка, пресс, распиловка, шлифовка', max_length=500, null=True, verbose_name='Участок'),
        ),
    ]
