# Generated by Django 3.2 on 2021-07-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210409_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form1',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form10',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form11',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form2',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form3',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form4',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form5',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form6',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form7',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form8',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='name_form9',
        ),
    ]
