# Generated by Django 3.1.4 on 2021-02-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='table_thickness_ground_plate_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_shift', models.CharField(max_length=1, null=True, verbose_name='Номер смены')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('value0', models.CharField(max_length=2, null=True, verbose_name='Толщина плиты')),
                ('value1', models.CharField(max_length=5, null=True, verbose_name='Значение 1')),
                ('value2', models.CharField(max_length=5, null=True, verbose_name='Значение 2')),
                ('value3', models.CharField(max_length=5, null=True, verbose_name='Значение 3')),
                ('value4', models.CharField(max_length=5, null=True, verbose_name='Значение 4')),
                ('value5', models.CharField(max_length=5, null=True, verbose_name='Значение 5')),
                ('value6', models.CharField(max_length=5, null=True, verbose_name='Значение 6')),
                ('value7', models.CharField(max_length=5, null=True, verbose_name='Значение 7')),
                ('value8', models.CharField(max_length=5, null=True, verbose_name='Значение 8')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Толщина плиты',
                'ordering': ('-date_created',),
            },
        ),
    ]
