# Generated by Django 3.1.4 on 2021-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_table_thickness_ground_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('value0', models.CharField(max_length=2, null=True)),
                ('value1', models.CharField(max_length=5, null=True)),
                ('value2', models.CharField(max_length=5, null=True)),
                ('value3', models.CharField(max_length=5, null=True)),
                ('value4', models.CharField(max_length=5, null=True)),
                ('value5', models.CharField(max_length=5, null=True)),
                ('value6', models.CharField(max_length=5, null=True)),
                ('value7', models.CharField(max_length=5, null=True)),
                ('value8', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Добавить значения толщины плиты',
                'verbose_name_plural': 'Добавить значение толщины плиты',
            },
        ),
    ]
