# Generated by Django 3.1.4 on 2021-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_table_thickness_ground_plate',
            name='number_shift',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
