# Generated by Django 3.1.4 on 2021-03-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_thickness_ground_plate_model',
            name='number_shift',
        ),
    ]
