# Generated by Django 3.1.4 on 2021-04-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_table_thickness_ground_plate_model_number_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePackBoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('value0', models.CharField(max_length=2, null=True, verbose_name='Толщина плиты')),
                ('value1', models.CharField(max_length=5, null=True, verbose_name='Значение 1')),
                ('value2', models.CharField(max_length=5, null=True, verbose_name='Значение 2')),
                ('value3', models.CharField(max_length=5, null=True, verbose_name='Значение 3')),
                ('value4', models.CharField(max_length=5, null=True, verbose_name='Значение 4')),
                ('value5', models.CharField(max_length=5, null=True, verbose_name='Значение 5')),
                ('value6', models.CharField(max_length=5, null=True, verbose_name='Значение 6')),
                ('value7', models.CharField(max_length=5, null=True, verbose_name='Значение 7')),
                ('value8', models.CharField(max_length=5, null=True, verbose_name='Значение 8')),
                ('value9', models.CharField(max_length=5, null=True, verbose_name='Значение 9')),
                ('value10', models.CharField(max_length=5, null=True, verbose_name='Значение 10')),
                ('value11', models.CharField(max_length=5, null=True, verbose_name='Значение 11')),
                ('value12', models.CharField(max_length=5, null=True, verbose_name='Значение 12')),
                ('value13', models.CharField(max_length=5, null=True, verbose_name='Значение 13')),
                ('value14', models.CharField(max_length=5, null=True, verbose_name='Значение 14')),
                ('value15', models.CharField(max_length=5, null=True, verbose_name='Значение 15')),
                ('value16', models.CharField(max_length=5, null=True, verbose_name='Значение 16')),
                ('value17', models.CharField(max_length=5, null=True, verbose_name='Значение 17')),
                ('value18', models.CharField(max_length=5, null=True, verbose_name='Значение 18')),
                ('value19', models.CharField(max_length=5, null=True, verbose_name='Значение 19')),
                ('value20', models.CharField(max_length=5, null=True, verbose_name='Значение 20')),
                ('value21', models.CharField(max_length=5, null=True, verbose_name='Значение 21')),
                ('value22', models.CharField(max_length=5, null=True, verbose_name='Значение 22')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Толщина пачки',
                'ordering': ('-date_created',),
            },
        ),
    ]
