# Generated by Django 3.1.4 on 2021-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_table_thickness_ground_plate_number_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_table_thickness_ground_plate',
            options={'verbose_name': 'поля', 'verbose_name_plural': 'Толщина плиты'},
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='number_shift',
            field=models.CharField(max_length=1, null=True, verbose_name='Номер смены'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value0',
            field=models.CharField(max_length=2, null=True, verbose_name='Толщина плиты'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value1',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 1'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value2',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 2'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value3',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 3'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value4',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 4'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value5',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 5'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value6',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 6'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value7',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 7'),
        ),
        migrations.AlterField(
            model_name='add_table_thickness_ground_plate',
            name='value8',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 8'),
        ),
    ]
