# Generated by Django 3.1.4 on 2021-02-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210201_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_table_thickness_ground_plate',
            new_name='table_thickness_ground_plate',
        ),
    ]
