# Generated by Django 3.1.4 on 2021-04-16 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210409_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_thickness_unprocessed_plate_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('value0', models.CharField(max_length=2, null=True, verbose_name='Толщина плиты')),
                ('value1', models.CharField(max_length=5, null=True, verbose_name='Значение 1')),
                ('value2', models.CharField(max_length=5, null=True, verbose_name='Значение 2')),
                ('value3', models.CharField(max_length=5, null=True, verbose_name='Значение 3')),
                ('value4', models.CharField(max_length=5, null=True, verbose_name='Значение 4')),
                ('value5', models.CharField(max_length=5, null=True, verbose_name='Значение 5')),
                ('value6', models.CharField(max_length=5, null=True, verbose_name='Значение 6')),
                ('value7', models.CharField(max_length=5, null=True, verbose_name='Значение 7')),
                ('value8', models.CharField(max_length=5, null=True, verbose_name='Значение 8')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Толщина нешлифованой плиты',
                'ordering': ('-date_created',),
            },
        ),
    ]
