# Generated by Django 3.1.4 on 2021-02-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210204_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_thickness_ground_plate',
            new_name='table_thickness_ground_plate_model',
        ),
    ]
