# Generated by Django 3.1.4 on 2021-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_list_thickness_unprocessed_plate_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_thickness_unprocessed_plate_model',
            name='value6',
        ),
        migrations.RemoveField(
            model_name='list_thickness_unprocessed_plate_model',
            name='value7',
        ),
        migrations.RemoveField(
            model_name='list_thickness_unprocessed_plate_model',
            name='value8',
        ),
    ]
