# Generated by Django 3.1.4 on 2021-04-16 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210416_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_thickness_unprocessed_plate_model',
            new_name='List_thickness_unpolished_plate_model',
        ),
    ]
