# Generated by Django 3.1.4 on 2021-04-16 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210416_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table_thickness_plate_model',
            new_name='Thickness_board_model',
        ),
        migrations.RenameModel(
            old_name='Table_Pack_Board_Model',
            new_name='Thickness_pack_board_model',
        ),
        migrations.RenameModel(
            old_name='List_thickness_unpolished_plate_model',
            new_name='Thickness_unpolished_board_model',
        ),
    ]
