# Generated by Django 3.2 on 2021-04-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_thickness_unpolished_pack_board_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_tapes_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата замены лент')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('number_1_1_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value0', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 1.1')),
                ('number_1_2_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value1', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 1.2')),
                ('number_2_1_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value2', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 2.1')),
                ('liner_2_1_choices', models.CharField(choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True)),
                ('number_2_2_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value3', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 2.2')),
                ('liner_2_2_choices', models.CharField(choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True)),
                ('number_2_3_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value4', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 2.3')),
                ('liner_2_3_choices', models.CharField(choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True)),
                ('number_2_4_choices', models.CharField(choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True)),
                ('value5', models.CharField(max_length=2, null=True, verbose_name='Пробег ленты Agg 2.4')),
                ('liner_2_4_choices', models.CharField(choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Учёт шлифовальных лент',
                'ordering': ('-date_created',),
            },
        ),
    ]
