# Generated by Django 3.2 on 2021-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_number_tapes_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value0',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 1.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value1',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 1.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value2',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 2.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value3',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 2.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value4',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 2.3'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='value5',
            field=models.CharField(max_length=20, null=True, verbose_name='Пробег ленты Agg 2.4'),
        ),
    ]
