# Generated by Django 3.2 on 2021-04-24 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20210418_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number_tapes_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Учёт шлифовальных лент'},
        ),
        migrations.AlterModelOptions(
            name='thickness_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Толщина шлифованной плиты'},
        ),
        migrations.AlterModelOptions(
            name='thickness_pack_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Толщина шлифованной пачки'},
        ),
        migrations.AlterModelOptions(
            name='thickness_unpolished_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Пресс - Толщина нешлифованой плиты'},
        ),
        migrations.AlterModelOptions(
            name='thickness_unpolished_pack_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Распиловка - Толщина не шлифованой пачки'},
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_1_1_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.1'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_1_2_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.2'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_1_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.1'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_2_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.2'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_3_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.3'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_4_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.4'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_3_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.3'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_4_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.4'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_1_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_1_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_3_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.3'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_4_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.4'),
        ),
        migrations.CreateModel(
            name='Lab_board_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Дата производства')),
                ('date_cr', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('number_shift', models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Смеена (производства)№')),
                ('number_path', models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Номер партии')),
                ('value0', models.CharField(max_length=4, verbose_name='Заказ')),
                ('value1', models.CharField(max_length=2, verbose_name='Толщина, мм')),
                ('value2', models.CharField(max_length=4, null=True, verbose_name='Длинна, мм')),
                ('value3', models.CharField(max_length=1, null=True, verbose_name='Количество, шт.')),
                ('value4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Комментарий')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Распиловка - Лабораторные образцы',
                'ordering': ('-date_created',),
            },
        ),
    ]
