# Generated by Django 3.2 on 2021-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210418_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number_tapes_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Учёт шлифовальных лент'},
        ),
        migrations.AlterModelOptions(
            name='thickness_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Толщина шлифованной плиты'},
        ),
        migrations.AlterModelOptions(
            name='thickness_pack_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Шлифвока - Толщина шлифованной пачки'},
        ),
        migrations.AlterModelOptions(
            name='thickness_unpolished_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Пресс - Толщина нешлифованой плиты'},
        ),
        migrations.AlterModelOptions(
            name='thickness_unpolished_pack_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Распиловка - Толщина не шлифованой пачки'},
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_1_1_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.1'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_1_2_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.2'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_1_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.1'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_2_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.2'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_3_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.3'),
        ),
        migrations.AddField(
            model_name='number_tapes_model',
            name='number_2_4_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.4'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_3_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.3'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='liner_2_4_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.4'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_1_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_1_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_1_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.1'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_2_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.2'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_3_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.3'),
        ),
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_2_4_choices',
            field=models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.4'),
        ),
    ]
