# Generated by Django 3.2 on 2021-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_lab_board_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_board_model',
            name='date_cr',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='lab_board_model',
            name='value1',
            field=models.CharField(max_length=2, verbose_name='Толщина, мм'),
        ),
        migrations.AlterField(
            model_name='lab_board_model',
            name='value2',
            field=models.CharField(max_length=4, null=True, verbose_name='Длинна, мм'),
        ),
        migrations.AlterField(
            model_name='lab_board_model',
            name='value3',
            field=models.CharField(max_length=1, null=True, verbose_name='Количество, шт.'),
        ),
        migrations.AlterField(
            model_name='lab_board_model',
            name='value4',
            field=models.CharField(max_length=30, null=True, verbose_name='Комментарий'),
        ),
    ]
