# Generated by Django 3.2 on 2021-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210424_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_board_model',
            name='date_cr',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab_board_model',
            name='value4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Комментарий'),
        ),
    ]
