# Generated by Django 3.2 on 2021-04-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210424_1352'),
        ('main', '0015_auto_20210424_1341'),
        ('main', '0015_auto_20210424_1343'),
        ('main', '0019_auto_20210424_1340'),
    ]

    operations = [
    ]
