# Generated by Django 3.2 on 2021-04-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20210424_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab_board_model',
            options={'verbose_name': 'поля', 'verbose_name_plural': 'Распиловка - Лабораторные образцы'},
        ),
        migrations.RemoveField(
            model_name='lab_board_model',
            name='date_cr',
        ),
    ]
