# Generated by Django 3.2 on 2021-04-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210424_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab_board_model',
        ),
    ]
