# Generated by Django 3.2 on 2021-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_lab_board_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number_tapes_model',
        ),
    ]
