# Generated by Django 3.2 on 2021-04-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_delete_number_tapes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_tapes_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата замены лент')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('number_1_1_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.1')),
                ('number_1_1_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.1')),
                ('value0', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 1.1')),
                ('number_1_2_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 1.2')),
                ('number_1_2_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 1.2')),
                ('value1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 1.2')),
                ('number_2_1_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.1')),
                ('number_2_1_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.1')),
                ('liner_2_1_choices', models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.1')),
                ('value2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 2.1')),
                ('number_2_2_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.2')),
                ('number_2_2_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.2')),
                ('liner_2_2_choices', models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.2')),
                ('value3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 2.2')),
                ('number_2_3_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.3')),
                ('number_2_3_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.3')),
                ('liner_2_3_choices', models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.3')),
                ('value4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 2.3')),
                ('number_2_4_choices', models.CharField(blank=True, choices=[('', ''), ('P 50', 'P 50'), ('P 80', 'P 80'), ('P 120', 'P 120')], max_length=20, null=True, verbose_name='Лента 2.4')),
                ('number_2_4_choices2', models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], max_length=20, null=True, verbose_name='Тип ленты 2.4')),
                ('liner_2_4_choices', models.CharField(blank=True, choices=[('', ''), ('Foam', 'Foam'), ('Pes', 'Pes')], max_length=20, null=True, verbose_name='Вставка 2.4')),
                ('value5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег ленты Agg 2.4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Шлифвока - Учёт шлифовальных лент',
                'ordering': ('-date_created',),
            },
        ),
    ]
