# Generated by Django 3.2 on 2021-04-24 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_number_tapes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_board_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Дата производства')),
                ('number_shift', models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Смеена (производства)№')),
                ('number_path', models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Номер партии')),
                ('value0', models.CharField(max_length=4, verbose_name='Заказ')),
                ('value1', models.CharField(max_length=2, verbose_name='Толщина, мм')),
                ('value2', models.CharField(max_length=4, null=True, verbose_name='Длинна, мм')),
                ('value3', models.CharField(max_length=1, null=True, verbose_name='Количество, шт.')),
                ('value4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Комментарий')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Распиловка - Лабораторные образцы',
                'ordering': ('-date_created',),
            },
        ),
    ]
