# Generated by Django 3.2 on 2021-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210424_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_tapes_model',
            name='number_1_1_choices2',
            field=models.CharField(blank=True, choices=[('', ''), ('Combi', 'Combi'), ('Polyster', 'Polyster')], default='P 50', max_length=20, null=True, verbose_name='Тип ленты 1.1'),
        ),
    ]
