# Generated by Django 3.2 on 2021-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_number_tapes_model_number_1_1_choices2'),
    ]

    operations = [
        migrations.AddField(
            model_name='thickness_unpolished_pack_board_model',
            name='value23',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 21'),
        ),
        migrations.AddField(
            model_name='thickness_unpolished_pack_board_model',
            name='value24',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 22'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value1',
            field=models.CharField(max_length=5, null=True, verbose_name='Зад толщ. после пресса, мм'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value10',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 8'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value11',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 9'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value12',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 10'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value13',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 11'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value14',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 12'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value15',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 13'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value16',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 14'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value17',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 15'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value18',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 16'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value19',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 17'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value2',
            field=models.CharField(max_length=2, null=True, verbose_name='Плит в пакете, шт'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value20',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 18'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value21',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 19'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value22',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 20'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value3',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 1'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value4',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 2'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value5',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 3'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value6',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 4'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value7',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 5'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value8',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 6'),
        ),
        migrations.AlterField(
            model_name='thickness_unpolished_pack_board_model',
            name='value9',
            field=models.CharField(max_length=5, null=True, verbose_name='Значение 7'),
        ),
    ]
