# Generated by Django 3.2 on 2021-07-13 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_auto_20210713_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thickness_unpolished_pack_board_model',
            options={'ordering': ('-date_created',), 'verbose_name': 'поля', 'verbose_name_plural': 'Распиловка - Толщина нешлифованой пачки'},
        ),
        migrations.CreateModel(
            name='Sizes_unpolished_board_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('value0', models.CharField(max_length=2, null=True, verbose_name='Толщина плиты')),
                ('value1', models.CharField(max_length=4, null=True, verbose_name='Ширина 2070(+/- 5 мм')),
                ('value2', models.CharField(max_length=4, null=True, verbose_name='Длинна правая сторона')),
                ('value3', models.CharField(max_length=4, null=True, verbose_name='Длинна левая сторона')),
                ('value4', models.CharField(max_length=1, null=True, verbose_name='Разница диагоналей')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'поля',
                'verbose_name_plural': 'Распиловка - Размеры нешлифованой плиты',
                'ordering': ('-date_created',),
            },
        ),
    ]
